Support specialized method-handle based lambdas
```
scala> (x: Int) => {??? : Int}
res2: Int => Int = $$Lambda$1371/1961176822@6ed3ccb2

scala> res2(42)
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at .$anonfun$1(<console>:8)
  at $$Lambda$1371/1961176822.apply$mcII$sp(Unknown Source)
  ... 33 elided

scala> (x: Int, y: Long) => {??? : Int}
res4: (Int, Long) => Int = $$Lambda$1382/1796047085@6f8e8894

scala> res4(0, 0L)
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at .$anonfun$1(<console>:8)
  at $$Lambda$1382/1796047085.apply$mcIIJ$sp(Unknown Source)
  ... 33 elided
```