SIP-23 Failing java varargs test
```
% scalac literal-type-java-varargs/JavaVarargs.java literal-type-java-varargs/test.scala
test.scala:2: error: type mismatch;
 found   : Array[1]
 required: Array[1]
Note: 1 <: 1, but class Array is invariant in type T.
You may wish to investigate a wildcard type such as `_ <: 1`. (SLS 3.2.10)
  val t: Array[1] = new JavaVarargs().foo[1](1)
                                            ^
```