WIP Load JDK classes from jrt:/ virtual FS on Java 9
status:
```
% qscala
Listening for transport dt_socket at address: 5006
Welcome to Scala 2.12.0-20160422-175308-dd3fa5b (Java HotSpot(TM) 64-Bit Server VM, Java 9-ea).
Type in expressions for evaluation. Or try :help.

scala> "".reverse
res0: String = ""

scala> "".reverse
res1: String = ""

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> "".reverse
java.lang.AssertionError: assertion failed: Failed to get the type of class symbol java.lang.invoke.MethodHandles$Lookup due to SI-9111.
	at scala.Predef$.assert(Predef.scala:219)
	at scala.tools.nsc.backend.jvm.BackendReporting$RightBiasedEither$.get$extension(BackendReporting.scala:59)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.visitInternalName$1(BackendUtils.scala:262)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils.scala$tools$nsc$backend$jvm$analysis$BackendUtils$$$anonfun$4(BackendUtils.scala:289)
	at scala.tools.nsc.backend.jvm
```