Use the recommended, and working, `sbt -warn`
In favour of `--warn`, which is broken in SBT 1.x.

Early commands are ones that are run before project load, in this case,
`-warn` used to mean `-` (schedule early) and `warn` (the command to
change log level)`.

`sbt-extras` translates its `-w` option into `--warn`, or passes through
`--warn` if provided. The official SBT launcher passes through `--warn`.

`sbt -warn` still works in 1.x, but `sbt --warn` doesn't give the non-zero
error code after a failure.

```
for sbt in 0.13.17 1.1.4; do for opt in "--warn" "-warn"; do (set -x; java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=$sbt $opt 'eval ???'; echo $?;) done; done
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=0.13.17 --warn 'eval ???'
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
...
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 1
1
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=0.13.17 -warn 'eval ???'
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
...
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 1
1
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=1.1.4 --warn 'eval ???'
[warn] sbt version mismatch, current: 1.1.4, in build.properties: "0.13.17", use 'reboot' to use the new value.
[info] Loading project definition from /tmp/scratch/project
[info] Updating ProjectRef(uri("file:/tmp/scratch/project/"), "scratch-build")...
[info] Done updating.
[info] Set current project to scratch (in build file:/tmp/scratch/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in a later version
[error] scala.NotImplementedError: an implementation is missing
[error]     at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
..
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 0
0
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=1.1.4 -warn 'eval ???'
+ echo 1
1
```

This commits changes our scripts to use the recommended `-warn`. However,
I'd say that SBT 1.x should either reject `--warn` outright or be compatible
with the old behaviour.