SI-8230 Pending test case for overloading, inference bug
    % scalac-hash v2.11.0-M7 -Ylog:typer -Dscalac.debug.tvar=true -uniqid  -Dscala.color test/pending/pos/t8230a.scala
    [    create] ?T3                      ( In I#arrToTrav[T3#14000] )
    [    create] ?T3                      ( In I#arrToTrav[T3#14000] )
    [   setInst] Long#2244                ( In I#arrToTrav[T3#14000], T3=Long#2244 )
    [    create] ?T2                      ( In Arr#apply[T2#8319] )
    [   setInst] Nothing#3013             ( In Arr#apply[T2#8319], T2=Nothing#3013 )
    [    create] ?T2                      ( In Arr#apply[T2#8319] )
    [    create] ?T3                      ( In I#arrToTrav[T3#14000] )
    [    create] ?T3                      ( In I#arrToTrav[T3#14000] )
    [   setInst] ?T2                      ( In I#arrToTrav[T3#14000], T3=?T2 )
    [log typer] implicit adapt failed: no type parameters for method arrToTrav#13999: (a#23600: Arr#7899[T3#23599])Traversable#2910[T3#23599] exist so that it can be applied to arguments (Arr#7899[?T2])
     --- because ---
    no unique instantiation of type variable T2#23596 could be found
    [log typer] fallback on implicits in adaptToArguments: Arr#7900.apply: Arr#7900
    test/pending/pos/t8230a.scala:14: error: type mismatch;
     found   : String#229("2")
     required: Long#2244
      val x: Traversable[Any] = Arr.apply("2")
                                          ^
    one error found

Inference of the type parameter `T3` of the implicit view is failing
because it is unable to instantiate the floating type variable
`?T2` of the viewee, `apply[?T2]("")`, which appears as a constraint
of `?T3`.