Avoid stub symbol related crash in backend
In this test case, the backend forces the specialization
info transform of `Sub` during computation of its
inner class metadata. This in turn runs the info transforms
of the `Base`. This leads to the uncurry info tranform
transforming a signature that has a type alias as a
method parameter type. Subsequent substution of the new
method symbol into the result type, which includes a
stub symbol for an absent class, tripped an assertion:

```
requirement failed: package b
java.lang.IllegalArgumentException: requirement failed: package b
	at scala.Predef$.require(Predef.scala:277)
	at scala.reflect.internal.Types$ModuleTypeRef.<init>(Types.scala:1879)
	at scala.reflect.internal.Types$PackageTypeRef.<init>(Types.scala:1897)
	at scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2401)
	at scala.reflect.internal.Types.typeRef(Types.scala:3553)
	at scala.reflect.internal.Types.typeRef$(Types.scala:3536)
	at scala.reflect.internal.SymbolTable.typeRef(SymbolTable.scala:16)
	at scala.reflect.internal.Symbols$TypeSymbol.newTypeRef(Symbols.scala:3026)
	at scala.reflect.internal.Symbols$TypeSymbol.updateTypeCache(Symbols.scala:3079)
	at scala.reflect.internal.Symbols$TypeSymbol.maybeUpdateTypeCache(Symbols.scala:3065)
	at scala.reflect.internal.Symbols$TypeSymbol.tpe_$times(Symbols.scala:3043)
	at scala.reflect.internal.Symbols$Symbol.typeOfThis(Symbols.scala:2020)
	at scala.reflect.internal.Types$ThisType.underlying(Types.scala:1184)
	at scala.reflect.internal.Types$SimpleTypeProxy.boundSyms(Types.scala:150)
	at scala.reflect.internal.Types$SimpleTypeProxy.boundSyms$(Types.scala:150)
	at scala.reflect.internal.Types$SingletonType.boundSyms(Types.scala:1088)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:726)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:789)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:102)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:102)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$Type.substSym(Types.scala:727)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:53)
	at scala.reflect.internal.transform.UnCurry.transformInfo(UnCurry.scala:154)
```

There are a number of possible ways to avoid this problem.
This commit starts by special casing `boundSyms` of `ThisType`
to return an empty list if the symbol is a stub.