Review for 8129
Filters out TypeVars instantiated to Nothing from constratints
before lubbing, without which pos/t8602.scala would regress.

Still got this problem:
```
[info] Running (fork) scala.tools.nsc.Main -usejavacp test/files/pos/t10722.scala
test/files/pos/t10722.scala:11: error: inferred kinds of the type arguments (Object,Test.Heads) do not conform to the expected kinds of the type parameters (type F,type G).
Object's type parameters do not match type F's expected parameters:
class Object has no type parameters, but type F has two
  flip(Tails("scala"): Coin[Int, String], Heads(50))
  ^
test/files/pos/t10722.scala:11: error: type mismatch;
 found   : Test.Coin[Int,String]
 required: F[Int,String]
  flip(Tails("scala"): Coin[Int, String], Heads(50))
                     ^
test/files/pos/t10722.scala:11: error: type mismatch;
 found   : Test.Heads[Int]
 required: G[Int]
  flip(Tails("scala"): Coin[Int, String], Heads(50))
                                               ^
three errors found
```