SI-9482 WIP try to hide ACC_SYNTHETIC members from user code
This breaks typechecking of desugared val patterns, not sure
how strike the right balance here.

```
⚡ qscalac -Xprint:typer test/files/pos/t122.scala
test/files/pos/t122.scala:3: error: not found: value x$1
  val (a:Int, b:Int) = (1, a)
       ^
test/files/pos/t122.scala:3: error: not found: value x$1
  val (a:Int, b:Int) = (1, a)
              ^
[[syntax trees at end of                     typer]] // t122.scala
package <empty> {
  class L extends scala.AnyRef {
    def <init>(): L = {
      L.super.<init>();
      ()
    };
    private[this] val v: Int = (immutable.this.List.apply[Int](2, (L.this.v: Int)): List[Int] @unchecked) match {
      case immutable.this.List.unapplySeq[Int](<unapply-selector>) <unapply> ((v @ (_: Int)), 2) => v
    };
    <stable> <accessor> def v: Int = L.this.v;
    <synthetic> <artifact> private[this] val x$1: (Int, Int) = (scala.Tuple2.apply[Int, Int](1, L.this.a): (Int, Int) @unchecked) match {
      case (_1: Int, _2: Int)(Int, Int)((a @ (_: Int)), (b @ (_: Int))) => scala.Tuple2.apply[Int, Int](a, b)
    };
    private[this] val a: Int = <x$1: error>.<_1: error>;
    <stable> <accessor> def a: Int = L.this.a;
    private[this] val b: Int = <x$1: error>.<_2: error>;
    <stable> <accessor> def b: Int = L.this.b
  }
}
```