SI-6656 Tighter variance checking
Reverts 68bcc9e7 so that we now issue the error:

    error: covariant type T occurs in invariant position in type T of type MyType
    class In[+T] { type MyType = T }
                    ^
regardless of whether and how `MyType` is used within `In`.